name: flutter_test_task_flora
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/arrows/arrow_right_b.svg
    - assets/arrows/arrow_right_w.svg
    - assets/background_vector/background_vector_5.svg
    - assets/background_vector/background_vector_17.svg
    - assets/background_vector/background_vector_16_r.svg
    - assets/background_vector/background_vector_16_b.svg
    - assets/background_vector/background_vector_15.svg
    - assets/background_vector/background_vector_14_r.svg
    - assets/background_vector/background_vector_14_b.svg
    - assets/background_vector/background_vector_11.svg
    - assets/background_vector/background_vector_10.svg
    - assets/background_vector/background_vector_9.svg
    - assets/background_vector/background_vector_6.svg
  
  fonts:
    - family: Nunito
      fonts:
          - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/nunito/Nunito-Regular.ttf
            weight: 400
          - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/nunito/Nunito-Medium.ttf
            weight: 500
          - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/nunito/Nunito-Light.ttf
            weight: 300
          - asset: assets/fonts/nunito/Nunito-Italic.ttf
            style: italic
          - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
            weight: 200
            style: italic
          - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
            weight: 800
            style: italic
          - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/nunito/Nunito-Bold.ttf
            weight: 700
          - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
            weight: 900
            style: italic
          - asset: assets/fonts/nunito/Nunito-Black.ttf
            weight: 900
